# costmap_params.yaml

/**:
  ros__parameters:
    use_sim_time: true

local_costmap:
  ros__parameters:
    update_frequency: 5.0
    publish_frequency: 2.0
    global_frame: odom
    robot_base_frame: base_footprint
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.05
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      ros__parameters:
        enabled: true
        scan_topic: /scan
        observation_sources: scan
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
        raytrace_range: 3.0
        inflation_radius: 0.3
        track_unknown_space: true
        footprint_padding: 0.015
        update_frequency: 5.0
        publish_frequency: 2.0
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      ros__parameters:
        enabled: true
        inflation_radius: 0.5
        cost_scaling_factor: 10.0

global_costmap:
  ros__parameters:
    update_frequency: 1.0
    publish_frequency: 1.0
    global_frame: map
    robot_base_frame: base_footprint
    resolution: 0.05
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      ros__parameters:
        map_topic: /map
        use_sim_time: true
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      ros__parameters:
        enabled: true
        scan_topic: /scan
        observation_sources: scan
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
        raytrace_range: 3.0
        inflation_radius: 0.3
        track_unknown_space: true
        footprint_padding: 0.015
        update_frequency: 1.0
        publish_frequency: 1.0
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      ros__parameters:
        enabled: true
        inflation_radius: 0.5
        cost_scaling_factor: 10.0